### ISSUE TITLE
XR Wallet / XR Pass Roadmap

### ISSUE THREAD

**Issue by dmitrizagidulin** [xr3ngine/xr3ngine#139]
This is a top-level / tracking epic for the XR Pass / XR Wallet (or whatever we decide to call it), that provides authentication, decentralized user profile storage,  (and in the future, digital signature, encryption).

**Low-level libs**:
* [x] Finish the [`did:web` DID resolver](https://github.com/interop-alliance/did-web-driver/). (in progress)
  * [x] Finish [`did-io`](https://github.com/digitalbazaar/did-io) refactoring (the DIDDocument class). 
    * [x] Finish [`crypto-ld`](https://github.com/digitalbazaar/crypto-ld) refactoring (enable pluggable key pair drivers).
    * [x] Extract ed25519-key-pair class to its own repo.
  *  [x] Implement `didWeb.generate()`.
  * [x] Implement `didWeb.get()`.

**Storage Server/Just-in-time Account Creation**:
* [ ] Implement [Credential Handler API (CHAPI)](https://github.com/digitalbazaar/credential-handler-polyfill) wallet provider in [life-server](https://github.com/interop-alliance/life-server) (in progress, PR life-server/51, 40% done)
  * [x] Have life-server generate its own DID and signing keys on installation
  * [x] Implement server provisioning a new DID (and keys) for a new user account
  * [x] Implement a super-basic WebKMS API on life-server
* [x] Implement an external User Account creation API so that xrchat-server can automatically provision new user accounts remotely

**Specs**:
* [ ] Specify a way for a CHAPI request to suggest a wallet to the user (if the user does not have one yet), and provide a callback uri to return from wallet registration.
* [ ] Specify the format of an XR Pass authentication credential.

**xr3ngine (front end)**:
* [ ] Wire up just-in-time account provisioning (registration for a wallet, creation of a storage user account, see above) when appropriate (on a purchase or when user wants to modify their avatar/settings)
* [ ] Implement wallet-based sign-in (would work cross-domain, on any compliant xr3ngine server).
* [ ] Modify User Profile UI to load (and save) their profile from their decentralized storage (that was).

**xr3ngine (back end)**:
* [ ] Have server generate its own DID and signing keys on installation
* [ ] Provide a proxy API for account provisioning (front-end would call the xr3ngine account provisioning API, which would in turn create a user storage account on the storage server)
* [ ] Implement a storage quota system (user can have X custom avatars for free, but beyond that should pay for more storage, etc) that serves as gatekeeper to the storage server.

**DevOps**:
* [ ] Register a domain for storage server
* [ ] Set up a VPS (on AWS or DigitalOcean) to host life-server in multi user mode (as a decentralized storage and wallet provider).
* [ ] Set up SMTP email server on storage server (for wallet account recovery)
* [ ] Set up exception monitoring on storage server
* [ ] Set up error log aggregation on storage server

**Comment by dmitrizagidulin** [comment]
Finished `crypto-ld` and `did-io` refactoring (at least enough for our purposes).
Now working on finishing the did:web driver library.

**Comment by shawticus** [comment]
This is exciting. Can we package this as a separate package with example under xrwallet, and then import it into client/server?

**Comment by mrhegemon** [comment]
Adrian Examples

https://github.com/exokitxr/zeo/blob/164f4c99451fc62222120f1c8c1887bec2976bad/core/engines/wallet/client.js#L115
https://github.com/exokitxr/zeo/issues/182

https://github.com/exokitxr/metaassembly-old/blob/736f5ec3619b057b5ed36f5fc4aae7a51b7c7229/extension/index.html#L76
https://github.com/exokitxr/metaassembly-old/blob/debb777d874ecb928c776a1fbc59dc1a962516d1/extension/trade.html#L161

**Comment by dmitrizagidulin** [comment]
Updated roadmap, implemented server generating its own DID Document on init.

@shawticus 
> Can we package this as a separate package with example under xrwallet, and then import it into client/server?

Partly, yeah. So on the server, it probably doesn't make sense to do a separate wallet package. Most of the work on the server will have to do with _removing_ stuff. (Removing the user registration, authentication, contact management, etc, etc, and moving that to the client.)
(To give you an idea of what the server-side code looks like for generating crypto keys & identifier on the server, look at https://github.com/interop-alliance/life-server/blob/add-wallet/bin/lib/init.js#L96 -- that part I think is fairly straightforward, doesn't need its own package.)

Now, on the client, yeah, we'll probably need a separate `xrwallet-client` repo.

**Comment by shawticus** [comment]
If we could make it an importable package on NPM that covers most of the
logic, individual hooks will still need to be added to our backend, it's
still going to need to have some boilerplate, configuration and
integration, but by pulling it out into it's own thing it can have value
outside of our backend, potentially could be the defacto way people are
doing wallets in our community-- as long as someone *can* connect their
ethereum to it and interop between the two then we can get full buy-in from
the Exokit community and make this a standard kind of thing.

**Comment by mrhegemon** [comment]
@dmitrizagidulin  - working through wallet deps. So, for example, various pre-req PRs for wallet stuff from yesterday: https://github.com/digitalbazaar/jsonld-signatures/pull/109, https://github.com/digitalbazaar/jws-linked-data-signature/pull/1, https://github.com/digitalbazaar/ed25519-signature-2018/pull/1,  and https://github.com/digitalbazaar/vc-js/pull/83 and updated https://github.com/interop-alliance/life-server/pull/61
